# Src : https://en.wikipedia.org/wiki/Wikipedia:List_of_English_contractions
CONTRACTIONS_DICT = {
#"ain't": "am not / are not / is not / has not / have not",
"ain't": "not",
#"aren't": "are not / am not",
"aren't": "be not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
#"he'd": "he had / he would",
"he'd": "he had",
"he'd've": "he would have",
#"he'll": "he shall / he will",
"he'll": "he will",
#"he'll've": "he shall have / he will have",
"he'll've": "he will have",
#"he's": "he has / he is",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
#"how's": "how has / how is / how does",
"how's": "how",
#"i'd": "i had / i would",
"i'd": "i had",
"i'd've": "i would have",
#"i'll": "i shall / i will",
"i'll": "i will",
#"i'll've": "i shall have / i will have",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
#"it'd": "it had / it would",
"it'd": "it had",
"it'd've": "it would have",
#"it'll": "it shall / it will",
"it'll": "it will",
#"it'll've": "it shall have / it will have",
"it'll've": "it will have",
#"it's": "it has / it is",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
#"she'd": "she had / she would",
"she'd": "she had",
"she'd've": "she would have",
#"she'll": "she shall / she will",
"she'll": "she will",
#"she'll've": "she shall have / she will have",
"she'll've": "she will have",
#"she's": "she has / she is",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
#"so's": "so as / so is",
"so's": "so is",
#"that'd": "that would / that had",
"that'd": "that had",
"that'd've": "that would have",
#"that's": "that has / that is",
"that's": "that is",
#"there'd": "there had / there would",
"there'd": "there had",
"there'd've": "there would have",
#"there's": "there has / there is",
"there's": "there is",
#"they'd": "they had / they would",
"they'd": "they had",
"they'd've": "they would have",
#"they'll": "they shall / they will",
"they'll": "they will",
#"they'll've": "they shall have / they will have",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
#"we'd": "we had / we would",
"we'd": "we had",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
#"what'll": "what shall / what will",
"what'll": "what will",
#"what'll've": "what shall have / what will have",
"what'll've": "what will have",
"what're": "what are",
#"what's": "what has / what is",
"what's": "what is",
"what've": "what have",
#"when's": "when has / when is",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
#"who'll": "who shall / who will",
"who'll": "who will",
#"who'll've": "who shall have / who will have",
"who'll've": "who will have",
#"who's": "who has / who is",
"who's": "who is",
"who've": "who have",
#"why's": "why has / why is",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
#"you'd": "you had / you would",
"you'd": "you had",
"you'd've": "you would have",
#"you'll": "you shall / you will",
"you'll": "you will",
#"you'll've": "you shall have / you will have",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}